[server]
address = "127.0.0.1"
headless = true
maxUploadSize = 25

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = false

[theme]
base = "light"
primaryColor = "#303a35"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f6f3"
textColor = "#242a27"
font = "sans-serif"
